import 'package:flangapp_app/enum/action_type.dart';
import 'package:flangapp_app/models/navigation_item.dart';

import '../enum/background_mode.dart';
import '../enum/load_indicator.dart';
import '../enum/template.dart';

class Config {

  /// Generated by SiteNative 23-07-2022 02:40:03
  /// App UID: 8a0ba4b7-cf02-8d84-b861-5288482344d8
  /// Version: https://hebadiaa.cf/backend/
  /// API server: {VERSION}

  /// *** App config *** ///
  // App name
  static String appName = "everydayscholarship";
  // App link
  static String appLink = "https://everydayscholarship.com/";
  // Display page name without app name (after 1 page)
  static bool displayTitle = true;
  // Main color (any HEX color)
  static String color = "#253C56";
  // Active color (any HEX color)
  static String activeColor = "#000000";
  // Icon color color (any HEX color)
  static String iconColor = "#000000";
  // Title color (true - white, false - black)
  static bool isDark = true;
  // Pull to refresh enabled
  static bool pullToRefresh = true;
  // User agent
  static String userAgent = "";
  // Admin email
  static String appEmail = "abdomazzek1@gmail.com";
  // Template
  static Template appTemplate = Template.drawer;
  // Loading indicator style
  static LoadIndicator indicator = LoadIndicator.line;
  // Loading indicator color
  static String indicatorColor = "#000000";

  /// *** Access ** ///
  // Access to camera
  static bool accessCamera = false;
  // Access to microphone
  static bool accessMicrophone = false;
  // Access to geolocation
  static bool accessLocation = false;

  /// *** Drawer settings *** ///
  // Title
  static String drawerTitle = "كل يوم منحة";
  // Subtitle
  static String drawerSubtitle = "كل يوم منحة";
  // Background mode
  static BackgroundMode drawerBackgroundMode = BackgroundMode.color;
  // Background color (any HEX color)
  static String drawerBackgroundColor = "#000000";
  // Title color (true - white, false - black)
  static bool drawerIsDark = true;
  // Background image name
  static String drawerBackgroundImage = "drawer_background.png";
  // Logo image name
  static String drawerLogoImage = "logo.png";
  // Display logo
  static bool drawerIsDisplayLogo = false;

  /// *** Splashscreen settings *** ///
  // Background color (any HEX color)
  static String splashBackgroundColor = "#0A0808";
  // Text color (any HEX color)
  static String splashTextColor = "#ffffff";
  // Is image background
  static bool splashIsBackgroundImage = true;
  // Background image name
  static String splashBackgroundImage = "splash_screen.png";
  // Tagline
  static String splashTagline = "كل يوم منحة";
  // Delay display (seconds)
  static int splashDelay = 3;
  // Logo image name
  static String splashLogoImage = "splash_logo.png";
  // Display logo
  static bool splashIsDisplayLogo = true;

  /// *** PUSH OneSignal settings *** ///
  // App ID
  static String osAppID = "";
  // Signing
  static String osSigning = "fc6c5efd0e430870ab1a104ea22b21623cdb72d49bb4c9497371b53e0189f74b";
  // Enabled android?
  static bool osAndroidEnabled = false;

  /// *** Website styles *** ///
  // List div for hide in app
  static List<String> cssHideBlock = [];

  /// *** Localization *** ///
  // Name offline image
  static String offlineImage = "wifi.png";
  // Error internet connection (offline)
  static String messageErrorOffline = "No internet connection";
  // Error open web page
  static String messageErrorBrowser = "Failed to load the page. Please try again later!";
  // Name error page image
  static String errorBrowserImage = "error.png";
  // Title about exit from app (Android)
  static String titleExit = "Confirmation";
  // Message about exit from app (Android)
  static String messageExit = "Are you sure you want to exit the app?";
  // Confirm button about
  static String actionYesDownload = "Yes";
  // Cancel button
  static String actionNoDownload = "No";
  // Contact us email (About screen)
  static String contactBtn = "Contact us with email";
  // Back
  static String backBtn = "Go back";

  /// *** Navigation *** ///
  // Main app navigation
  static List<NavigationItem> mainNavigation = [
    	NavigationItem(name: "قناة يوتيوب",icon: "logo-youtube.svg",type: ActionType.external,value: "https://www.youtube.com/channel/UCfT2NO2Uef2ZbYTxordT4RA",),
	NavigationItem(name: "انستجرام",icon: "logo-instagram.svg",type: ActionType.external,value: "https://www.instagram.com/everyday_scholarship_/",),
	NavigationItem(name: "واتس اب",icon: "logo-whatsapp.svg",type: ActionType.external,value: "https://chat.whatsapp.com/Ebpyw0LDVIoIrx6IyCcSzH",),
	NavigationItem(name: "فيس بوك",icon: "logo-facebook.svg",type: ActionType.external,value: "https://www.facebook.com/groups/2589682374498098/",),
	NavigationItem(name: "موقعنا",icon: "logo-web-component.svg",type: ActionType.internal,value: "https://everydayscholarship.com/",),

  ];
  // Bar app navigation
  static List<NavigationItem> barNavigation = [
    
  ];
  // Modal navigation
  static List<NavigationItem> modalNavigation = [
    
  ];
}